language: python
python:
  - 2.7
  - 3.3

before_install:
  - nvm install 4.2.4
  - npm install
  - npm run build
  - pip install -r test-requirements.txt

install:
  - pip install -r requirements.txt

# command to run tests
script:  
  - coverage run -p -m nose
  - coverage combine
  - coverage report -m
#after_success:
#  - coveralls
